version: "3.8"

services:
  db:
    image: postgres:14.6
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - main

  app:
    build:
      context: .
    env_file:
      - .env
    networks:
      - main
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db

networks:
  main:

volumes:
  database-data:
  prometheus-data:
  grafana-data:
